name: Start a run from Python file on local server via self-hosted Github Actions runner

on:
  push:

jobs:
  start-local-run:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install kfp
        pip install scikit-learn
        
    - name: Connect to local server and run the Notebook
      run: |       
        python src/helpers/components/main_pipeline.py
